### ISSUE TITLE
Docker導入

### ISSUE THREAD

**Issue by BARBARCHAN** [BARBARCHAN/responsive_checker_app#4]
環境依存せずに開発環境を構築するため

**Comment by BARBARCHAN** [comment]
## 次回やること

以下エラーの解決

```yaml
junshiro@junshironoMacBook-Pro responsive_checker_app % docker-compose build
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.web.build contains an invalid type, it should be a string, or an object
```

**Comment by BARBARCHAN** [comment]
解決した

`build:`の後ろに`.`を加えた

```yaml
version: '3'
services:
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/responsive_checker_app/
      # - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    container_name: responsive_checker_app
  db:
    image: mysql:5.6
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    tty: true
volumes:
  mysql_data:
  bundle:
```

### 解決方法

1.拡張機能`YAML`が原因箇所を教えてくれた
![image](https://user-images.githubusercontent.com/70783556/174479461-cc3a0b2a-67aa-4a6d-9760-0833f4bcba6f.png)


2.[Docker-docs-ja](https://docs.docker.jp/index.html)を参照
